### PR TITLE
Fix CVEs (vulnerabilities)

### PR DESCRIPTION
**Pull request by vavsab**
Fixes all CVEs that were fixed in [osmtogeojson](https://github.com/tyrasd/osmtogeojson/pull/136)

### CODE REVIEW

**Comment by vavsab** [comment]
@plepe Could you please take a look at this pr?

**Comment by vavsab** [comment]
FYI: One test was failing before the change and after the change.
image

**Comment by plepe** [comment]
Thanks for the contribution! I published the new package right away :-)

About the tests - I think there's something wrong, because in total there are over 300 tests. Did you create the test/conf.json file and does your local Overpass server work (see "Development" in the README file).

**Comment by vavsab** [comment]
Yeah. Did everything as the instructions say. It's ok as far as it works on your local machine.

Thank you a lot for quick response. It will help my company to fix CVEs and pass certification. Updating my project right now to get the new version...

**Pull request merged**
